import type { Recipient } from "./types";

export const recipientsData: Recipient[] = [
  { email: "ann@timescale.com", isSelected: false },
  { email: "bob@timescale.com", isSelected: false },
  { email: "emma@timescale.com", isSelected: false },
  { email: "daniel@timescale.com", isSelected: true },
  { email: "noah@timescale.com", isSelected: false },
  { email: "harper@timescale.com", isSelected: false },
  { email: "lucas@timescale.com", isSelected: true },
  { email: "brian@qwerty.com", isSelected: true },
  { email: "james@qwerty.com", isSelected: false },
  { email: "kate@qwerty.com", isSelected: true },
  { email: "chris@qwerty.com", isSelected: true },
  { email: "olivia@qwerty.com", isSelected: false },
  { email: "liam@qwerty.com", isSelected: true },
  { email: "sarah@qwerty.com", isSelected: false },
  { email: "henry@qwerty.com", isSelected: true },
  { email: "jane@awesome.com", isSelected: false },
  { email: "sophia@awesome.com", isSelected: true },
  { email: "mia@awesome.com", isSelected: false },
  { email: "william@awesome.com", isSelected: true },
  { email: "elijah@awesome.com", isSelected: false },
  { email: "nora@awesome.com", isSelected: true },
  { email: "mike@hello.com", isSelected: true },
  { email: "lucas@hello.com", isSelected: false },
  { email: "ethan@hello.com", isSelected: true },
  { email: "ava@hello.com", isSelected: false },
  { email: "jackson@hello.com", isSelected: true },
  { email: "amelia@hello.com", isSelected: false },

  { email: "alex@techcorp.com", isSelected: false },
  { email: "brad@techcorp.com", isSelected: true },
  { email: "claire@techcorp.com", isSelected: false },
  { email: "derek@techcorp.com", isSelected: true },
  { email: "eva@techcorp.com", isSelected: false },
  { email: "ryan@startuphub.com", isSelected: true },
  { email: "kelly@startuphub.com", isSelected: false },
  { email: "sam@startuphub.com", isSelected: true },
  { email: "tina@startuphub.com", isSelected: false },
  { email: "victor@startuphub.com", isSelected: true },
  { email: "josh@cloudbase.com", isSelected: false },
  { email: "megan@cloudbase.com", isSelected: true },
  { email: "paul@cloudbase.com", isSelected: false },
  { email: "rachel@cloudbase.com", isSelected: true },
  { email: "steven@cloudbase.com", isSelected: false },
];
